export const ORDER_ACTION_TYPES = {
  ORDERS_REQUEST: "ORDERS_REQUEST",
  ORDERS_SUCCESS: "ORDERS_SUCCESS",
  ORDERS_FAILURE: "ORDERS_FAILURE",

  ORDER_DETAILS_REQUEST: "ORDER_DETAILS_REQUEST",
  ORDER_DETAILS_SUCCESS: "ORDER_DETAILS_SUCCESS",
  ORDER_DETAILS_FAILURE: "ORDER_DETAILS_FAILURE",

  ORDER_CANCEL_REQUEST: "ORDER_CANCEL_REQUEST",
  ORDER_CANCEL_SUCCESS: "ORDER_CANCEL_SUCCESS",
  ORDER_CANCEL_FAILURE: "ORDER_CANCEL_FAILURE",

  CLEAR_ORDER_ERROR: "CLEAR_ORDER_ERROR",
  CLEAR_ORDER_DETAILS: "CLEAR_ORDER_DETAILS",
};
