export const CART_ACTION_TYPES = {
  CART_REQUEST: "CART_REQUEST",
  CART_SUCCESS: "CART_SUCCESS",
  CART_FAILURE: "CART_FAILURE",

  CART_ADD_REQUEST: "CART_ADD_REQUEST",
  CART_ADD_SUCCESS: "CART_ADD_SUCCESS",
  CART_ADD_FAILURE: "CART_ADD_FAILURE",

  CART_UPDATE_REQUEST: "CART_UPDATE_REQUEST",
  CART_UPDATE_SUCCESS: "CART_UPDATE_SUCCESS",
  CART_UPDATE_FAILURE: "CART_UPDATE_FAILURE",

  CART_REMOVE_REQUEST: "CART_REMOVE_REQUEST",
  CART_REMOVE_SUCCESS: "CART_REMOVE_SUCCESS",
  CART_REMOVE_FAILURE: "CART_REMOVE_FAILURE",

  CART_CLEAR_REQUEST: "CART_CLEAR_REQUEST",
  CART_CLEAR_SUCCESS: "CART_CLEAR_SUCCESS",
  CART_CLEAR_FAILURE: "CART_CLEAR_FAILURE",

  CLEAR_CART_ERROR: "CLEAR_CART_ERROR",
};
