export const WISHLIST_REQUEST = "WISHLIST_REQUEST";
export const WISHLIST_SUCCESS = "WISHLIST_SUCCESS";
export const WISHLIST_FAILURE = "WISHLIST_FAILURE";

export const WISHLIST_ADD_REQUEST = "WISHLIST_ADD_REQUEST";
export const WISHLIST_ADD_SUCCESS = "WISHLIST_ADD_SUCCESS";
export const WISHLIST_ADD_FAILURE = "WISHLIST_ADD_FAILURE";

export const WISHLIST_REMOVE_REQUEST = "WISHLIST_REMOVE_REQUEST";
export const WISHLIST_REMOVE_SUCCESS = "WISHLIST_REMOVE_SUCCESS";
export const WISHLIST_REMOVE_FAILURE = "WISHLIST_REMOVE_FAILURE";

export const WISHLIST_CLEAR_REQUEST = "WISHLIST_CLEAR_REQUEST";
export const WISHLIST_CLEAR_SUCCESS = "WISHLIST_CLEAR_SUCCESS";
export const WISHLIST_CLEAR_FAILURE = "WISHLIST_CLEAR_FAILURE";
