export const REVIEW_ACTION_TYPES = {
  CREATE_REQUEST: "REVIEW_CREATE_REQUEST",
  CREATE_SUCCESS: "REVIEW_CREATE_SUCCESS",
  CREATE_FAILURE: "REVIEW_CREATE_FAILURE",

  GET_REQUEST: "REVIEW_GET_REQUEST",
  GET_SUCCESS: "REVIEW_GET_SUCCESS",
  GET_FAILURE: "REVIEW_GET_FAILURE",

  UPDATE_REQUEST: "REVIEW_UPDATE_REQUEST",
  UPDATE_SUCCESS: "REVIEW_UPDATE_SUCCESS",
  UPDATE_FAILURE: "REVIEW_UPDATE_FAILURE",

  DELETE_REQUEST: "REVIEW_DELETE_REQUEST",
  DELETE_SUCCESS: "REVIEW_DELETE_SUCCESS",
  DELETE_FAILURE: "REVIEW_DELETE_FAILURE",

  CLEAR_ERROR: "REVIEW_CLEAR_ERROR",
};