export const USER_DASHBOARD_ACTION_TYPES = {
  DASHBOARD_REQUEST: "USER_DASHBOARD_REQUEST",
  DASHBOARD_SUCCESS: "USER_DASHBOARD_SUCCESS",
  DASHBOARD_FAILURE: "USER_DASHBOARD_FAILURE",
  CLEAR_DASHBOARD_ERROR: "CLEAR_DASHBOARD_ERROR",
  CLEAR_DASHBOARD: "CLEAR_DASHBOARD",
};
