export const USER_PROFILE_ACTION_TYPES = {
  PROFILE_REQUEST: "USER_PROFILE_REQUEST",
  PROFILE_SUCCESS: "USER_PROFILE_SUCCESS",
  PROFILE_FAILURE: "USER_PROFILE_FAILURE",

  UPDATE_PROFILE_REQUEST: "USER_PROFILE_UPDATE_REQUEST",
  UPDATE_PROFILE_SUCCESS: "USER_PROFILE_UPDATE_SUCCESS",
  UPDATE_PROFILE_FAILURE: "USER_PROFILE_UPDATE_FAILURE",

  CLEAR_PROFILE_ERROR: "USER_PROFILE_CLEAR_ERROR",
  CLEAR_PROFILE: "USER_PROFILE_CLEAR",
};