export const ADMIN_DASHBOARD_REQUEST = "ADMIN_DASHBOARD_REQUEST";
export const ADMIN_DASHBOARD_SUCCESS = "ADMIN_DASHBOARD_SUCCESS";
export const ADMIN_DASHBOARD_FAILURE = "ADMIN_DASHBOARD_FAILURE";

export const ADMIN_USERS_REQUEST = "ADMIN_USERS_REQUEST";
export const ADMIN_USERS_SUCCESS = "ADMIN_USERS_SUCCESS";
export const ADMIN_USERS_FAILURE = "ADMIN_USERS_FAILURE";

export const ADMIN_ORDERS_REQUEST = "ADMIN_ORDERS_REQUEST";
export const ADMIN_ORDERS_SUCCESS = "ADMIN_ORDERS_SUCCESS";
export const ADMIN_ORDERS_FAILURE = "ADMIN_ORDERS_FAILURE";

export const ADMIN_PROFILE_REQUEST = "ADMIN_PROFILE_REQUEST";
export const ADMIN_PROFILE_SUCCESS = "ADMIN_PROFILE_SUCCESS";
export const ADMIN_PROFILE_FAILURE = "ADMIN_PROFILE_FAILURE";

export const ADMIN_REPORT_REQUEST = "ADMIN_REPORT_REQUEST";
export const ADMIN_REPORT_SUCCESS = "ADMIN_REPORT_SUCCESS";
export const ADMIN_REPORT_FAILURE = "ADMIN_REPORT_FAILURE";

export const ADMIN_VERIFICATION_REQUEST = "ADMIN_VERIFICATION_REQUEST";
export const ADMIN_VERIFICATION_SUCCESS = "ADMIN_VERIFICATION_SUCCESS";
export const ADMIN_VERIFICATION_FAILURE = "ADMIN_VERIFICATION_FAILURE";

export const ADMIN_PENDING_SELLERS_REQUEST = "ADMIN_PENDING_SELLERS_REQUEST";
export const ADMIN_PENDING_SELLERS_SUCCESS = "ADMIN_PENDING_SELLERS_SUCCESS";
export const ADMIN_PENDING_SELLERS_FAILURE = "ADMIN_PENDING_SELLERS_FAILURE";

export const ADMIN_PENDING_PRODUCTS_REQUEST = "ADMIN_PENDING_PRODUCTS_REQUEST";
export const ADMIN_PENDING_PRODUCTS_SUCCESS = "ADMIN_PENDING_PRODUCTS_SUCCESS";
export const ADMIN_PENDING_PRODUCTS_FAILURE = "ADMIN_PENDING_PRODUCTS_FAILURE";

export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST";
export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS";
export const ADMIN_PRODUCT_FAILURE = "ADMIN_PRODUCT_FAILURE";