export const PRODUCT_ACTION_TYPES = {
  PRODUCTS_REQUEST: "PRODUCTS_REQUEST",
  PRODUCTS_SUCCESS: "PRODUCTS_SUCCESS",
  PRODUCTS_FAILURE: "PRODUCTS_FAILURE",

  PRODUCT_REQUEST: "PRODUCT_REQUEST",
  PRODUCT_SUCCESS: "PRODUCT_SUCCESS",
  PRODUCT_FAILURE: "PRODUCT_FAILURE",

  PRODUCT_MUTATION_REQUEST: "PRODUCT_MUTATION_REQUEST",
  PRODUCT_MUTATION_SUCCESS: "PRODUCT_MUTATION_SUCCESS",
  PRODUCT_MUTATION_FAILURE: "PRODUCT_MUTATION_FAILURE",

  CLEAR_PRODUCT_ERROR: "CLEAR_PRODUCT_ERROR",
  CLEAR_SELECTED_PRODUCT: "CLEAR_SELECTED_PRODUCT",
};
