export const PAYMENT_ACTION_TYPES = {
  CREATE_REQUEST: "PAYMENT_CREATE_REQUEST",
  CREATE_SUCCESS: "PAYMENT_CREATE_SUCCESS",
  CREATE_FAILURE: "PAYMENT_CREATE_FAILURE",

  VERIFY_REQUEST: "PAYMENT_VERIFY_REQUEST",
  VERIFY_SUCCESS: "PAYMENT_VERIFY_SUCCESS",
  VERIFY_FAILURE: "PAYMENT_VERIFY_FAILURE",

  GET_REQUEST: "PAYMENT_GET_REQUEST",
  GET_SUCCESS: "PAYMENT_GET_SUCCESS",
  GET_FAILURE: "PAYMENT_GET_FAILURE",

  CLEAR_ERROR: "PAYMENT_CLEAR_ERROR",
  RESET: "PAYMENT_RESET",
};
