export const SELLER_ACTION_TYPES = {
  APPLICATION_REQUEST: "SELLER_APPLICATION_REQUEST",
  APPLICATION_SUCCESS: "SELLER_APPLICATION_SUCCESS",
  APPLICATION_FAILURE: "SELLER_APPLICATION_FAILURE",

  PROFILE_REQUEST: "SELLER_PROFILE_REQUEST",
  PROFILE_SUCCESS: "SELLER_PROFILE_SUCCESS",
  PROFILE_FAILURE: "SELLER_PROFILE_FAILURE",

  PROFILE_UPDATE_REQUEST: "SELLER_PROFILE_UPDATE_REQUEST",
  PROFILE_UPDATE_SUCCESS: "SELLER_PROFILE_UPDATE_SUCCESS",
  PROFILE_UPDATE_FAILURE: "SELLER_PROFILE_UPDATE_FAILURE",

  DASHBOARD_REQUEST: "SELLER_DASHBOARD_REQUEST",
  DASHBOARD_SUCCESS: "SELLER_DASHBOARD_SUCCESS",
  DASHBOARD_FAILURE: "SELLER_DASHBOARD_FAILURE",

  ORDERS_REQUEST: "SELLER_ORDERS_REQUEST",
  ORDERS_SUCCESS: "SELLER_ORDERS_SUCCESS",
  ORDERS_FAILURE: "SELLER_ORDERS_FAILURE",

  ORDER_REQUEST: "SELLER_ORDER_REQUEST",
  ORDER_SUCCESS: "SELLER_ORDER_SUCCESS",
  ORDER_FAILURE: "SELLER_ORDER_FAILURE",

  ORDER_STATUS_REQUEST: "SELLER_ORDER_STATUS_REQUEST",
  ORDER_STATUS_SUCCESS: "SELLER_ORDER_STATUS_SUCCESS",
  ORDER_STATUS_FAILURE: "SELLER_ORDER_STATUS_FAILURE",

  CLEAR_ERROR: "SELLER_CLEAR_ERROR",
  CLEAR_SELECTED_ORDER: "SELLER_CLEAR_SELECTED_ORDER",
};
